### PR TITLE
Fix error chan close on channel shutdown.

### PR DESCRIPTION
**Pull request by DmitriyMV**
If errors chan remains open after rabbimq channel shutdown, it could result in deadlock when other goroutine is trying to Close channel again.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@DmitriyMV can you please add a test? I assume by "rabbitmq channel shutdown" you mean a channel exception that causes RabbitMQ to close the channel.

**Comment by DmitriyMV** [comment]
Yes, sorry for the incorrect description. In my case this happened when I tried to close the Channel after acknowleding delivery from consumer with autoAck (my incorrect application logic which resulted in channel level exception). Next step is too confirm that it's a reliable way of reproducing this error and writing the proper unit test. Will do.

**Comment by michaelklishin** [comment]
@DmitriyMV thank you for the update.

**Comment by DmitriyMV** [comment]
Sorry - my initial assumption was incorrect. The deadlock happens when you try to concurrently close channel and it's connection. You may require several attempts to reproduce it (usually 2-3 times).

The commit above fixes it.

**Comment by DmitriyMV** [comment]
Is there anything that stops from merging this branch?

**Comment by michaelklishin** [comment]
@DmitriyMV it needs QA. Chances are it may not happen until January 3rd or so.

**Comment by michaelklishin** [comment]
Merging per discussion with @streadway and @gerhard.

**Pull request merged**
