### PR TITLE
Ensuring the TLS handshake doesn't stall forever by providing a deadline

### PR DESCRIPTION
**Pull request by joliver**
This would resolve issue #165

### CODE REVIEW

**Comment by joliver** [comment]
@streadway Is there anything I can do to get this merged in? We've hit this bug a number of times in production now.

**Comment by streadway** [comment]
Thanks for the reminder.

The `defaultDialer` already has [SetReadDeadline](https://github.com/smartystreets/amqp/blob/master/connection.go#L114)

Are you using a custom dialer? If not, please change the `defaultDialer` to `SetDeadline` since it looks like the TLS client handshake writes first.

**Comment by joliver** [comment]
I'm using the `defaultDialer`.

Here's the trick. There are *two* deadlines that ned to be set&mdash;the dial timeout, which you have, and the TLS handshake timeout, which you're missing.

Ironically, I identified [this exact same issue](https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/5b03d351fe83c294021d3b18f71d369e78cb2017) in the official RabbitMQ .NET client library about two years ago. You can see my name in the comment for that commit.

**Comment by streadway** [comment]
Yup - the TCP handshake deadline is handled in https://github.com/smartystreets/amqp/blob/master/connection.go#L108-L111

From there it's an optional TLS handshake and then the first messages of an AMQP handshake before heartbeating will check the liveliness of the connection.

It looks like SetReadTimeout in defaultDialer will timeout on the server sent TLS ServerHello read already. But if using TLS, it won't timeout on the AMQP ConnectionStart read.

I understand that Set*Timeout will wait for the next (single) IO operation, which means both the read and write timeout would be met on the first messages of the [TLS handshake](https://golang.org/src/crypto/tls/handshake_client.go#L140) before the AMQP handshake begins.  Since we don't control the timeouts between reads and writes within the tls package, I'm inclined to look at handshaking of TCP, TLS and AMQP under the same connection timeout.

This can be validated if TLS termination is separate from AMQP termination. TLS succeeds but AMQP stalls - the connection would hang.

It sounds like a better alternative would be to start the heartbeater as soon as the TCP session is established and reconfigure it with whatever the client and server negotiate during the AMQP connection handshake.

Do you think you could make the tests necessary to timeout on stalled TLS and also timeout on successful TLS but stalled AMQP to reproduce this bug?

**Comment by joliver** [comment]
I definitely like the idea of a single timeout for the TCP, TLS, and AMQP handshake process. If we don't have a full AMQP connection, we should definitely tear down what we've got.

I might be able to create a reproducible test case, but I'll have to investigate how possible it is to mock the various aspects of the connection.

**Comment by streadway** [comment]
Take a look at https://github.com/smartystreets/amqp/blob/master/tls_test.go which gets through a TLS handshake into an incomplete AMQP handshake.

From there you can look at https://golang.org/pkg/testing/iotest/#TruncateWriter to simulate a network partition.

**Comment by michaelklishin** [comment]
We agreed to start small and use the same timeout value for each "stage": TCP connection, TLS upgrade, AMQP 0-9-1 handshake. Context propagation may come in the future.

**Comment by michaelklishin** [comment]
@gerhard and I tried to simulate a TLS handshake timeout and after a good hour or so we have some findings:

 * Go's TLS implementation is good enough that it complains about specific issues such as oversized records (when a TLS client connects to a non-TLS server) or unknown CA certificate (non-TLS client to a TLS server, a common scenario that times out with some clients and I believe `openssl s_client`)
 * As far as I can tell, Go's standard library exposes only one timeout for each connection type, and while it's probably possible to configure TLS handshake timeout, it is not trivial to test just that part without modifying this client's code
 * We investigated how Go's HTTP transport implements TLS handshake timeouts for HTTPS. It does so in the transport's own code (by setting up a one-off timer), presumably because of the point above.

Therefore we believe further attempts at testing specifically the TLS handshake timeout is not worth the time it is taking. The patch is quite trivial and we've done the same thing in at least one official client in the past.

**Comment by michaelklishin** [comment]
Manually applied in master, thank you @joliver!

**Pull request closed without merging**
