### PR TITLE
Never send any frames after connection shutdown

### PR DESCRIPTION
**Pull request by abrander**
We should never send any frames after shutdown. Doing so can easily result in deadlocks.

This PR fixes this deadlock by using a `closed` field on the Connection type which will be set upon `shutdown()`.

### CODE REVIEW

**Comment by abrander** [comment]
I think this fixes issue #173 and #180. Maybe even #147 and #150.

**Comment by lud4ik** [comment]
Interesting. Can you describe, please, scenarious that your commit fixes.
Did it fixed your case and have been tested?

**Comment by abrander** [comment]
It can be reproduced fairly simple:

```go
connection := amqp.Dial(...)
for {
    chan, _ := connection.Channel()
    fmt.Printf("We're alive %p\n", chan)
    chan.Close()
}
```

Run a loop like this in a few hundred goroutines while restarting the peer (we did `rabbitctl stop_app && rabbitctl start_app` once a second). It would deadlock for us within a few seconds.

The race took some hard work and a lot of packet captures to find ;)

A function (In this case `Channel.open()` called from `Connection.Channel()`) calling `Channel.call()` when doing RPC will send a `*channelOpen` which will trigger `Channel.call()`'s `select{}` waiting for a reply.

Imagine this:
The serverside (or anyone else) closes the connection.
The client receives a `*connectionClose` and starts `Connection.shutdown()` immediately (in another goroutine).
Someone calls `Connection.Channel()` *before* `Connection.shutdown()` reaches `me.conn.Close()`.
The `*channelOpen` frame *will* be sent and `Channel.rpc()` will be waiting for a reply or error that will never arrive.
Boom. Deadlock in `Channel.call()`.

All RPC functions are susceptible to this deadlock. One can look for `wait()` functions in `spec091.go` returning true.

`grep -P "^\treturn true" spec091.go  -B 1` should give you an idea.

This PR makes sure no frames are ever sent if we're in the process of shutting down for whatever reason.

I'm not sure if it's tested enough or not. We have had it running for a few days on multiple nodes hammering packages close to line speed while fuzzing the network and restarting RabbitMQ without encountering any deadlocks (after applying #187 and #188). We don't use streadway/amqp to consume thou.

**Comment by lud4ik** [comment]
Thank you for explanation.
Issue [173](https://github.com/streadway/amqp/issues/173) is about the same select in Channel.call.
We tried to solve it by closing rpc or errors chan on channel close for having also closed flag for connection - so on connection shutdown it should close channel, where it should close chan, from which it was waiting in select in call method. We could't find how it could happen than Channel open was invoked without Close on connection shutdown. 
I am happy for you if it works...
But let me show you the hole:
```
// Performs a request/response call for when the message is not NoWait and is
// specified as Synchronous.
func (me *Channel) call(req message, res ...message) error {
	if err := me.send(me, req); err != nil {
		return err
	}
        // what if connection shutdown happen here? 
	if req.wait() {
		select {
		case e := <-me.errors:
			return e

		case msg := <-me.rpc:
			if msg != nil {
				for _, try := range res {
					if reflect.TypeOf(msg) == reflect.TypeOf(try) {
						// *res = *msg
						vres := reflect.ValueOf(try).Elem()
						vmsg := reflect.ValueOf(msg).Elem()
						vres.Set(vmsg)
						return nil
					}
				}
				return ErrCommandInvalid
			} else {
				// RPC channel has been closed without an error, likely due to a hard
				// error on the Connection.  This indicates we have already been
				// shutdown and if were waiting, will have returned from the errors chan.
				return ErrClosed
			}
		}
	}

	return nil
}
```
Your decision solves only if close connection happen before send.

**Comment by abrander** [comment]
Interesting. That would fail if the *client* closes the connection (because `Connection.shutdown()` will be called with a `nil` argument as the error, and therefor never triggering the error handling in `Channel.shutdown()`), but would work as expected when server side closes the connection (Connection.shutdown() will be called like this `me.shutdown(newError(m.ReplyCode, m.ReplyText))`).

We have been testing server side dying/closing/disappearing randomly - therefor never seen this case were the client introduces a race :-/

I think a fix would be in `Channel.shutdown()`. Replace:
```go
		// Notify RPC if we're selecting
		if e != nil {
			me.errors <- e
		}
```

with 

```go
		// Notify RPC if we're selecting
		if e == nil {
			e = ErrClosed
		}

		select {
		case me.errors <- e:
		default:
		}
```

It's untested thou.

**Comment by lud4ik** [comment]
>That would fail if the client closes the connection (because Connection.shutdown() will be called with a nil argument as the error

We tried version where it closed errors chan regardless errors or nil.  I think it could be reproduced playing with Sleep.

**Comment by lud4ik** [comment]
```
select {
        case me.errors <- e:
        default:
        }
```
Default case is redundant, errors chan is bufered and to errors chan is written only in descructor, which is called only once according to struct types

**Comment by michaelklishin** [comment]
I'd extract `atomic.LoadInt32(&me.closed) == 1` into a predicate but otherwise it looks good (and very similar to what other client libraries do).

**Comment by michaelklishin** [comment]
Merged in #223. Thank you!

**Pull request closed without merging**
